spring:
  application:
    name: "ecommerce"

  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true
    username: "user"
    password: "root"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate

  liquibase:
    enabled: true
#    drop-first: true
    change-log: classpath:db/changelog/changelog-master.yml

api:
  security:
    token:
      secret: "chave-teste-apenas-de-dev-para-prod-use-env"
      expiration-hours: 1