services:
  mysql:
    image: mysql:9.2
    container_name: mysql-db
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=ecommerce_db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=root
      - MYSQL_ALLOW_EMPTY_PASSWORD=no
      - MYSQL_ROOT_HOST=%
      - TZ=America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network

#  dbgate:
#    image: dbgate/dbgate
#    container_name: dbgate_app
#    ports:
#      - "3000:3000"
#    environment:
#      - DB_GATE_PORT=3000
#    depends_on:
#      - mysql
#    restart: always
#    networks:
#      - app-network

networks:
  app-network:
    driver: bridge
volumes:
  mysql-data:
